# vim: fyletype=sh
export CONFIGS="${HOME}/workspace/configs/bash"

source ${CONFIGS}/bashenv
source ${CONFIGS}/bash_alias

##
# Your previous /Users/conall/.bash_profile file was backed up as /Users/conall/.bash_profile.macports-saved_2013-09-25_at_12:40:51
##

# MacPorts Installer addition on 2013-09-25_at_12:40:51: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/conall/.bash_profile file was backed up as /Users/conall/.bash_profile.macports-saved_2013-11-30_at_13:23:00
##

# MacPorts Installer addition on 2013-11-30_at_13:23:00: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/conall/.bash_profile file was backed up as /Users/conall/.bash_profile.macports-saved_2013-12-26_at_16:37:05
##

# MacPorts Installer addition on 2013-12-26_at_16:37:05: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/conall/.bash_profile file was backed up as /Users/conall/.bash_profile.macports-saved_2014-01-26_at_14:01:16
##

# MacPorts Installer addition on 2014-01-26_at_14:01:16: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/conall/.bash_profile file was backed up as /Users/conall/.bash_profile.macports-saved_2015-09-02_at_16:53:27
##

# MacPorts Installer addition on 2015-09-02_at_16:53:27: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

