export PATH=$PATH:$HOME/bin/:/usr/local/bin:/opt/local/bin

test -r /sw/bin/init.sh && . /sw/bin/init.sh

source ~/.bash_alias
source ~/.bashenv

##
# Your previous /Users/conall/.bash_profile file was backed up as /Users/conall/.bash_profile.macports-saved_2010-09-21_at_19:11:09
##

# MacPorts Installer addition on 2010-09-21_at_19:11:09: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

